// 3Lowz portfolio — content model (lifted from the original site)
window.RESUME = {
  name: '3Lowz',
  role: 'Freelance Senior Software Engineer',
  intro: "A decade of crafting software across startups, consultancies, and international teams. I thrive where architecture meets code — building systems that are as clean under the hood as they are effective on the surface.",
  portrait: '../../assets/portrait.jpg',
  social: [
    { label: 'GitHub', icon: 'bi bi-github', href: 'https://github.com/3Lowz' },
    { label: 'LinkedIn', icon: 'bi bi-linkedin', href: 'https://www.linkedin.com/in/hdaneluz/' },
  ],
  nav: ['About', 'Skills', 'Experience', 'Blog', 'Showcase'],
  // `level` = self-rated proficiency 0–100, drives the fill bars.
  skills: [
    { group: 'Programming Languages', items: [
      { name: 'TypeScript', icon: 'devicon-typescript-plain', level: 98 },
      { name: 'NodeJS', icon: 'devicon-nodejs-plain', level: 97 },
      { name: 'Python', icon: 'devicon-python-plain', level: 98 },
      { name: 'PHP', icon: 'devicon-php-plain', level: 76 },
      { name: 'Go', icon: 'devicon-go-original-wordmark', level: 85 },
    ]},
    { group: 'Others (personal)', items: [
      { name: 'Rust', icon: 'devicon-rust-original', level: 72 },
      { name: 'C++', icon: 'devicon-cplusplus-plain', level: 56 },
      { name: 'Elixir', icon: 'devicon-elixir-plain', level: 52 },
    ]},
    { group: 'Frontend', items: [
      { name: 'React', icon: 'devicon-react-plain', level: 99 },
      { name: 'Rx', icon: 'devicon-rxjs-plain', level: 85 },
      { name: 'd3', icon: 'devicon-d3js-plain', level: 83 },
      { name: 'Wasm', icon: 'devicon-wasm-plain', level: 73 },
      { name: 'Webpack', icon: 'devicon-webpack-plain', level: 88 },
      { name: 'Rollup', icon: 'devicon-rollup-plain', level: 85 },
      { name: 'Backbone', icon: 'devicon-backbonejs-plain', level: 80 },
    ]},
    { group: 'Web Frameworks', items: [
      { name: 'Fastify', icon: 'devicon-fastify-plain', level: 98 },
      { name: 'Express', icon: 'devicon-express-original', level: 92 },
      { name: 'Django', icon: 'devicon-django-plain', level: 97 },
      { name: 'Flask', icon: 'devicon-flask-plain', level: 81 },
      { name: 'FastAPI', icon: 'devicon-fastapi-plain-wordmark', level: 82 },
      { name: 'Symfony', icon: 'devicon-symfony-original', level: 86 },
    ]},
    { group: 'Databases', items: [
      { name: 'MySQL', icon: 'devicon-mysql-plain', level: 97 },
      { name: 'Postgres', icon: 'devicon-postgresql-plain', level: 91 },
      { name: 'Mongo', icon: 'devicon-mongodb-plain', level: 85 },
      { name: 'Redis', icon: 'devicon-redis-plain', level: 87 },
    ]},
    { group: 'Clouds & OS', items: [
      { name: 'AWS', icon: 'devicon-amazonwebservices-plain-wordmark', level: 92 },
      { name: 'GCP', icon: 'devicon-googlecloud-plain', level: 87 },
      { name: 'Linux', icon: 'devicon-linux-plain', level: 100 },
      { name: 'macOS', icon: 'devicon-apple-plain', level: 100 },
      { name: 'Windows', icon: 'devicon-windows11-plain', level: 95 },
    ]},
  ],
  experience: [
    { company: 'Extark Srl', place: 'Udine', period: "Aug '24 — current", title: 'Software Engineer · Hybrid', current: true,
      stack: ['Python', 'Pandas', 'NumPy', 'FastAPI', 'Django', 'React', 'Angular', 'MySQL', 'Postgres', 'Redis', 'Symfony', 'GCP'] },
    { company: 'WeDigital Srl', place: 'Pordenone', period: "Aug '22 — Aug '24", title: 'Software Engineer · Hybrid',
      stack: ['NestJS', 'Fastify', 'SocketIO', 'TypeORM', 'TypeScript', 'React-ReduxSaga', 'Webpack federation', 'MySQL', 'Mongo', 'AWS', 'Kubernetes'] },
    { company: 'Musircle Ltd', place: 'London', period: "Sep '23 — Feb '24", title: 'Software Engineer · Remote',
      stack: ['NestJS', 'GraphQL', 'TypeScript', 'React', 'Recoil', 'Mongo', 'Redis', 'AWS', 'Docker', 'Nginx'] },
    { company: 'ItEquipe Srls', place: 'Pordenone', period: "Aug '21 — Jul '22", title: 'Software Engineer · Remote',
      stack: ['Django', 'NumPy', 'Tastypie', 'React-Native', 'TypeScript', 'D3js', 'MySQL', 'Nginx', 'Gunicorn'] },
    { company: 'Consultant', place: 'Udine', period: "Sep '18 — Dec '20", title: 'Software Specialist · Hybrid',
      stack: ['TypeScript', 'React-Native', 'Python', 'C/C++', 'PHP', 'Java', 'PostgreSQL', 'Docker', 'Kubernetes', 'K3s'] },
    { company: 'Fullstack Agency', place: 'Rome', period: "Sep '16 — Feb '17", title: 'Lead Web Developer · Remote',
      stack: ['ExpressJS', 'Ionic', 'Angular', 'React-Redux-Thunk', 'MongoDB', 'DigitalOcean', 'Nginx'] },
    { company: 'Delta Askii Srl', place: 'Udine', period: "Oct '14 — Jul '16", title: 'Lead Web Developer · Hybrid',
      stack: ['HapiJS', 'ExpressJS', 'SocketIO', 'RxJS', 'Angular', 'React/Redux', 'D3js', 'Laravel', 'MySQL', 'MongoDB'] },
    { company: 'uForge / Canton Srl', place: 'Pordenone', period: "Oct '12 — May '14", title: 'Web Developer · Co-Founder',
      stack: ['Django', 'BackboneJS', 'Angular', 'PostgreSQL', 'Redis', 'Cordova/PhoneGap', 'Heroku'] },
  ],
};
