# Site settings
title: 3lowz's
description: A small overview upon me
email: hdaneluz@gmail.com
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://3lowz.github.io" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  3lowz

# Build settings
markdown: kramdown
remote_theme: pages-themes/dinky@v0.2.0
plugins:
  - jekyll-remote-theme

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
